
// This file was auto-generated by ML.NET Model Builder.

using System;

namespace SampleClassification.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            SampleClassification.ModelInput sampleData = new SampleClassification.ModelInput()
            {
                UDI = 161,
                Product_ID = @"L47340",
                Type = @"L",
                Air_temperature = 298.4F,
                Process_temperature = 308.2F,
                Rotational_speed = 1282F,
                Torque = 60.7F,
                Tool_wear = 216F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = SampleClassification.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Machine_failure with predicted Machine_failure from sample data...\n");
            Console.WriteLine($"Predicted Machine_failure: {predictionResult.PredictedLabel}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
